### ISSUE TITLE
spec leads to failure

### ISSUE THREAD

**Issue by dennym** [RailsApps/rails3-bootstrap-devise-cancan#36]
I did a clean `git clone` and `bundle install`. Any Idea?

> bundle exec rake spec                                                                                                                                                                                      >!1539
> /package/host/localhost/ruby-1.9.3-p0/bin/ruby -S rspec ./spec/controllers/home_controller_spec.rb ./spec/controllers/users_controller_spec.rb ./spec/models/user_spec.rb
> FF..F.FF......FF
> 
> Failures:
> 
> 1) UsersController GET 'show' should find the right user
>     Failure/Error: @user = FactoryGirl.create(:user)
>     ActiveRecord::StatementInvalid:
>       SQLite3::SQLException: near "SAVEPOINT": syntax error: SAVEPOINT >active_record_1
>     # ./spec/controllers/users_controller_spec.rb:6:in `block (2 levels) in <top (required)>'
> 
>  2) UsersController GET 'show' should be successful
>     Failure/Error: @user = FactoryGirl.create(:user)
>     ActiveRecord::StatementInvalid:
>       SQLite3::SQLException: near "SAVEPOINT": syntax error: SAVEPOINT >active_record_1
>     # ./spec/controllers/users_controller_spec.rb:6:in `block (2 levels) in <top (required)>'
> 
>  3) User should reject duplicate email addresses
>     Failure/Error: User.create!(@attr)
>     ActiveRecord::StatementInvalid:
>       SQLite3::SQLException: near "SAVEPOINT": syntax error: SAVEPOINT >active_record_1
>     # ./spec/models/user_spec.rb:40:in `block (2 levels) in <top (required)>'
> 
>  4) User should reject email addresses identical up to case
>     Failure/Error: User.create!(@attr.merge(:email => upcased_email))
>     ActiveRecord::StatementInvalid:
>       SQLite3::SQLException: near "SAVEPOINT": syntax error: SAVEPOINT >active_record_1
>     # ./spec/models/user_spec.rb:47:in `block (2 levels) in <top (required)>'
> 
>  5) User should create a new instance given a valid attribute
>     Failure/Error: User.create!(@attr)
>     ActiveRecord::StatementInvalid:
>       SQLite3::SQLException: near "SAVEPOINT": syntax error: SAVEPOINT >active_record_1
>     # ./spec/models/user_spec.rb:15:in `block (2 levels) in <top (required)>'
> 
>  6) User password encryption should set the encrypted password attribute
>     Failure/Error: @user = User.create!(@attr)
>     ActiveRecord::StatementInvalid:
>       SQLite3::SQLException: near "SAVEPOINT": syntax error: SAVEPOINT >active_record_1
>     # ./spec/models/user_spec.rb:90:in `block (3 levels) in <top (required)>'
> 
>  7) User password encryption should have an encrypted password attribute
>     Failure/Error: @user = User.create!(@attr)
>     ActiveRecord::StatementInvalid:
>       SQLite3::SQLException: near "SAVEPOINT": syntax error: SAVEPOINT >active_record_1
>     # ./spec/models/user_spec.rb:90:in `block (3 levels) in <top (required)>'
> 
> Finished in 0.83859 seconds
> 16 examples, 7 failures
> 
> Failed examples:
> 
> rspec ./spec/controllers/users_controller_spec.rb:17 # UsersController GET 'show' >should find the right user
> rspec ./spec/controllers/users_controller_spec.rb:12 # UsersController GET 'show' >should be successful
> rspec ./spec/models/user_spec.rb:39 # User should reject duplicate email addresses
> rspec ./spec/models/user_spec.rb:45 # User should reject email addresses identical up to case
> rspec ./spec/models/user_spec.rb:14 # User should create a new instance given a valid attribute
> rspec ./spec/models/user_spec.rb:97 # User password encryption should set the encrypted password attribute
> rspec ./spec/models/user_spec.rb:93 # User password encryption should have an encrypted password attribute
> 
> Randomized with seed 59467

**Comment by dennym** [comment]
Was an error with my sqlite version. Using CentOS5 and had to config my bundler to use other sqlite version.
http://shynnergy.com/2012/07/savepoint-exception-with-rails-3-1-on-jenkins/
