### ISSUE TITLE
`undefined method 'flatten' for nil:NilClass` error in tests

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-bootstrap-devise-cancan#38]
Currently, after cloning the example app, a test error is emitted:

```
Feature: Sign in
  Scenario: User is not signed up         # features/users/sign_in.feature:6
    And I should be signed out            # features/step_definitions/user_steps.rb:142
      undefined method `flatten' for nil:NilClass (NoMethodError)
      /home/mark/.rvm/gems/ruby-1.9.3-p392@global/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/database_statements.rb:348:in `rollback_transaction_records'
      /home/mark/.rvm/gems/ruby-1.9.3-p392@global/gems/database_cleaner-1.0.0.RC1/lib/database_cleaner/active_record/transaction.rb:36:in `clean'
      /home/mark/.rvm/gems/ruby-1.9.3-p392@global/gems/database_cleaner-1.0.0.RC1/lib/database_cleaner/base.rb:77:in `clean'
      /home/mark/.rvm/gems/ruby-1.9.3-p392@global/gems/database_cleaner-1.0.0.RC1/lib/database_cleaner/configuration.rb:79:in `block in clean'
      /home/mark/.rvm/gems/ruby-1.9.3-p392@global/gems/database_cleaner-1.0.0.RC1/lib/database_cleaner/configuration.rb:79:in `each'
      /home/mark/.rvm/gems/ruby-1.9.3-p392@global/gems/database_cleaner-1.0.0.RC1/lib/database_cleaner/configuration.rb:79:in `clean'
      /home/mark/.rvm/gems/ruby-1.9.3-p392@global/gems/cucumber-rails-1.3.1/lib/cucumber/rails/hooks/database_cleaner.rb:9:in `After'
```

My versions:

```
$ bundle exec cucumber --version
1.2.3
$ bundle exec rails -v
Rails 3.2.13
$ bundle exec ruby -v
ruby 1.9.3p392 (2013-02-22 revision 39386) [i686-linux]
```

**Comment by MarkDBlackwell** [comment]
Would something like this [pull request](https://github.com/RailsApps/rails3-devise-rspec-cucumber/pull/45) (regarding another Rails Example Apps' Cucumber configuration) help resolve this error?

**Comment by MarkDBlackwell** [comment]
When the app is regenerated, the error goes away.
